<?php
/*
 * Copyright 2013 Coinapult
 *
 *  This file is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.

 *  This file is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.

 *  You should have received a copy of the GNU General Public License.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Ira Miller (ira@coinapult.com)
 */

$order = $this->getOrder();
$adata = $order->getPayment->getAdditionalData();

if(!empty($adata) && property_exists($adata, "BitcoinTotal")) {
?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px;">Bitcoin Payment Details</th>
        </tr>
    </thead>

    <tbody>
        <tr><td style="padding-right: 3em;">Coinapult Order ID:</td><td><?php echo $adata->CoinapultTID; ?></td></tr>
        <tr><td style="padding-right: 3em;">Bitcoin Address:</td><td><?php echo $adata->BitcoinAddress; ?></td></tr>
        <tr><td style="padding-right: 3em;">Bitcoin Total:</td><td><?php echo $adata->BitcoinTotal; ?> btc</td></tr>
    </tbody>
</table>
<?php
}
?>
